CREATE DATABASE db_mhs

use db_mhs

CREATE TABLE M_FAKULTAS_053 (
K_FAKULTAS varchar(3) PRIMARY KEY,
SINGKAT varchar(10),
CONTENT varchar(45)
)

CREATE TABLE M_JENJANG_053 (
K_JENJANG varchar(3) PRIMARY KEY,
SINGKAT varchar(10),
CONTENT varchar(30)
)

CREATE TABLE M_JURUSAN_053 (
K_JURUSAN varchar(3) PRIMARY KEY,
K_JENJANG varchar(3) FOREIGN KEY REFERENCES M_JENJANG_053(K_JENJANG),
K_FAKULTAS varchar(3) FOREIGN KEY REFERENCES M_FAKULTAS_053(K_FAKULTAS),
SINGKAT varchar(10),
CONTENT varchar(45)
)

CREATE TABLE M_PROG_STUDI_053 (
K_PROG_STUDI varchar(3) PRIMARY KEY,
K_FAKULTAS varchar(3) FOREIGN KEY REFERENCES M_FAKULTAS_053(K_FAKULTAS),
K_JENJANG varchar(3) FOREIGN KEY REFERENCES M_JENJANG_053(K_JENJANG),
K_JURUSAN varchar(3) FOREIGN KEY REFERENCES M_JURUSAN_053(K_JURUSAN),
SINGKAT varchar(10),
CONTENT varchar(60)
)

CREATE TABLE M_KELAS_053 (
K_KELAS varchar(3) PRIMARY KEY,
SINGKAT varchar(10),
CONTENT varchar(45)
)

CREATE TABLE M_SELEKSI_053 (
K_SELEKSI varchar(3) PRIMARY KEY,
SINGKAT varchar(10),
CONTENT varchar(45)
)

CREATE TABLE M_CABANG_053 (
K_CABANG varchar(3) PRIMARY KEY,
SINGKAT varchar(10),
CONTENT varchar(45)
)

CREATE TABLE MAHASISWA_053 (
NIM varchar(15) PRIMARY KEY,
NAMA varchar(60),
ANGKATAN int,
K_JURUSAN varchar(3) FOREIGN KEY REFERENCES M_JURUSAN_053(K_JURUSAN),
K_JENJANG varchar(3) FOREIGN KEY REFERENCES M_JENJANG_053(K_JENJANG),
K_FAKULTAS varchar(3) FOREIGN KEY REFERENCES M_FAKULTAS_053(K_FAKULTAS),
K_PROG_STUDI varchar(3) FOREIGN KEY REFERENCES M_PROG_STUDI_053(K_PROG_STUDI),
K_SELEKSI varchar(3) FOREIGN KEY REFERENCES M_SELEKSI_053(K_SELEKSI),
K_KELAS varchar(3)  FOREIGN KEY REFERENCES M_KELAS_053(K_KELAS),
K_CABANG varchar(3) FOREIGN KEY REFERENCES M_CABANG_053(K_CABANG)
)

CREATE TABLE M_NEGARA_053 (
K_NEGARA varchar(9) PRIMARY KEY,
CONTENT varchar(45)
)

CREATE TABLE M_PROPINSI_053 (
K_PROPINSI varchar(9) PRIMARY KEY,
K_NEGARA varchar(9) FOREIGN KEY REFERENCES M_NEGARA_053(K_NEGARA),
CONTENT varchar(100)
)

CREATE TABLE M_KOTA_053 (
K_KOTA varchar(9) PRIMARY KEY,
K_NEGARA varchar(9) FOREIGN KEY REFERENCES M_NEGARA_053(K_NEGARA),
K_PROPINSI varchar(9) FOREIGN KEY REFERENCES M_PROPINSI_053(K_PROPINSI),
CONTENT varchar(100)
)

CREATE TABLE MHS_KOTA_053 (
NIM varchar(15) FOREIGN KEY REFERENCES MAHASISWA_053(NIM),
K_PROPINSI varchar(9) FOREIGN KEY REFERENCES M_PROPINSI_053(K_PROPINSI),
K_NEGARA varchar(9) FOREIGN KEY REFERENCES M_NEGARA_053(K_NEGARA),
K_KOTA varchar(9) FOREIGN KEY REFERENCES M_KOTA_053(K_KOTA),
ALAMAT varchar(100),
KODE_POS varchar(9)
)

ALTER TABLE MHS_KOTA_053
ALTER COLUMN NIM VARCHAR(15) NOT NULL; 

ALTER TABLE MHS_KOTA_053
ADD CONSTRAINT PK_MHS_KOTA_053 PRIMARY KEY (NIM);
 
ALTER TABLE MHS_KOTA_053
ALTER COLUMN ALAMAT VARCHAR(110);

ALTER TABLE MHS_KOTA_053
ALTER COLUMN KODE_POS VARCHAR(6); 

SELECT COLUMN_NAME, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MHS_KOTA_053'
SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'MHS_KOTA_053' 

CREATE TABLE MHS_KOTA2_053 (
NIM varchar(15) FOREIGN KEY REFERENCES MAHASISWA_053(NIM),
K_PROPINSI varchar(9) FOREIGN KEY REFERENCES M_PROPINSI_053(K_PROPINSI),
K_NEGARA varchar(9) FOREIGN KEY REFERENCES M_NEGARA_053(K_NEGARA),
K_KOTA varchar(9) FOREIGN KEY REFERENCES M_KOTA_053(K_KOTA),
ALAMAT varchar(100),
KODE_POS varchar(9)
)

SELECT COLUMN_NAME, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MHS_KOTA2_053'
SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'MHS_KOTA2_053' 

DROP TABLE MHS_KOTA_053

DROP DATABASE db_mhs